---
# IIaC Workstation Playbook
-

  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local

  # Vars: variables that will apply to the play, on all targets 

  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    - name: Set wsl2_environment fact default to False
      set_fact:
        wsl2_environment: False
    - name: Set wsl2_environment fact True
      set_fact:
        wsl2_environment: True
      when: ansible_kernel is search("microsoft-standard-WSL2")
    - name: Display wsl2_environment 
      debug:
        msg: "WSL2 = {{ wsl2_environment }}"


  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task


  # Roles: list of roles to be imported into the play
    
- 
  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  become: true

  # Vars: variables that will apply to the play, on all targets 


  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    - name: Display wsl2_environment in roles play 
      debug:
        msg: "WSL2 = {{ wsl2_environment }} in Roles play"

  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task


  # Roles: list of roles to be imported into the play
  roles:
    - role: xanmanning.virtualbox
      when: not wsl2_environment
      
    - role: diodonfrost.vagrant
...